### ISSUE TITLE
Installation under Debian Jessie is not tested

### ISSUE THREAD

**Issue by dortegau** [idealista/solrcloud_role#71]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

This role is not tested under Debian Jessie, but `meta/main.yml` says that could be installed under this OS.

**Comment by sorobon** [comment]
Debian Jessie is not supported yet. The EOL will be the 30 June, 2020.
https://wiki.debian.org/LTS
